/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelBookingSystem;

import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author 21145050
 */
public class View extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        this.setVisible(true);
        this.MainMenuPanel.setVisible(true); // Specifies the main menu as visible while other menus start invisable.
        this.BookingMenuPanel.setVisible(false);
        this.RoomMenuPanel.setVisible(false);
        this.GuestMenuPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuPanel = new javax.swing.JPanel();
        HotelBookingSystemLabel = new javax.swing.JLabel();
        SelectMenuLabel = new javax.swing.JLabel();
        RoomMenuButton = new javax.swing.JButton();
        BookingMenuButton = new javax.swing.JButton();
        GuestMenuButton = new javax.swing.JButton();
        QuitButton = new javax.swing.JButton();
        RoomMenuPanel = new javax.swing.JPanel();
        RoomMenuLabel = new javax.swing.JLabel();
        MainMenuButtonR = new javax.swing.JButton();
        RoomScrollPane = new javax.swing.JScrollPane();
        RoomTextArea = new javax.swing.JTextArea();
        RoomsLabel = new javax.swing.JLabel();
        AddRoomButton = new javax.swing.JButton();
        RemoveRoomButton = new javax.swing.JButton();
        BookingMenuPanel = new javax.swing.JPanel();
        BookingMenuLabel = new javax.swing.JLabel();
        MainMenuButtonB = new javax.swing.JButton();
        BookingScrollPane = new javax.swing.JScrollPane();
        BookingTextArea = new javax.swing.JTextArea();
        BookingsLabel = new javax.swing.JLabel();
        AddBookingButton = new javax.swing.JButton();
        RemoveBookingButton = new javax.swing.JButton();
        GuestMenuPanel = new javax.swing.JPanel();
        GuestMenuLabel = new javax.swing.JLabel();
        MainMenuButtonG = new javax.swing.JButton();
        GuestScrollPane = new javax.swing.JScrollPane();
        GuestTextArea = new javax.swing.JTextArea();
        GuestsLabel = new javax.swing.JLabel();
        AddGuestButton = new javax.swing.JButton();
        RemoveGuestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Booking System");

        MainMenuPanel.setMinimumSize(new java.awt.Dimension(330, 173));
        MainMenuPanel.setPreferredSize(new java.awt.Dimension(330, 173));

        HotelBookingSystemLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HotelBookingSystemLabel.setText("Hotel Booking System");

        SelectMenuLabel.setText("Select a menu to open:");

        RoomMenuButton.setText("Rooms");

        BookingMenuButton.setText("Bookings");
        BookingMenuButton.setMinimumSize(new java.awt.Dimension(72, 22));

        GuestMenuButton.setText("Guests");

        QuitButton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        QuitButton.setText("Quit");

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                        .addComponent(SelectMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                        .addComponent(HotelBookingSystemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(GuestMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuPanelLayout.createSequentialGroup()
                        .addComponent(RoomMenuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BookingMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainMenuPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(HotelBookingSystemLabel)
                .addGap(18, 18, 18)
                .addComponent(SelectMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomMenuButton)
                    .addComponent(GuestMenuButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RoomMenuPanel.setMaximumSize(new java.awt.Dimension(330, 173));
        RoomMenuPanel.setMinimumSize(new java.awt.Dimension(330, 173));

        RoomMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RoomMenuLabel.setText("Room Menu");

        MainMenuButtonR.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MainMenuButtonR.setText("Main Menu");

        RoomTextArea.setEditable(false);
        RoomTextArea.setColumns(30);
        RoomTextArea.setRows(5);
        RoomScrollPane.setViewportView(RoomTextArea);

        RoomsLabel.setText("Rooms:");

        AddRoomButton.setText("Add");
        AddRoomButton.setToolTipText("");
        AddRoomButton.setActionCommand("AddR");

        RemoveRoomButton.setText("Remove");
        RemoveRoomButton.setActionCommand("RemoveR");

        javax.swing.GroupLayout RoomMenuPanelLayout = new javax.swing.GroupLayout(RoomMenuPanel);
        RoomMenuPanel.setLayout(RoomMenuPanelLayout);
        RoomMenuPanelLayout.setHorizontalGroup(
            RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RoomMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainMenuButtonR)
                .addContainerGap())
            .addGroup(RoomMenuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomsLabel)
                    .addGroup(RoomMenuPanelLayout.createSequentialGroup()
                        .addComponent(RoomScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveRoomButton)
                            .addComponent(AddRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        RoomMenuPanelLayout.setVerticalGroup(
            RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoomMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomMenuLabel)
                    .addComponent(MainMenuButtonR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoomsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RoomMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomMenuPanelLayout.createSequentialGroup()
                        .addComponent(AddRoomButton)
                        .addGap(5, 5, 5)
                        .addComponent(RemoveRoomButton))
                    .addComponent(RoomScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BookingMenuPanel.setMaximumSize(new java.awt.Dimension(330, 173));
        BookingMenuPanel.setMinimumSize(new java.awt.Dimension(330, 173));

        BookingMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BookingMenuLabel.setText("Booking Menu");

        MainMenuButtonB.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MainMenuButtonB.setText("Main Menu");

        BookingTextArea.setEditable(false);
        BookingTextArea.setColumns(30);
        BookingTextArea.setRows(5);
        BookingScrollPane.setViewportView(BookingTextArea);

        BookingsLabel.setText("Bookings:");

        AddBookingButton.setText("Add");
        AddBookingButton.setActionCommand("AddB");

        RemoveBookingButton.setText("Remove");
        RemoveBookingButton.setActionCommand("RemoveB");

        javax.swing.GroupLayout BookingMenuPanelLayout = new javax.swing.GroupLayout(BookingMenuPanel);
        BookingMenuPanel.setLayout(BookingMenuPanelLayout);
        BookingMenuPanelLayout.setHorizontalGroup(
            BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookingMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainMenuButtonB)
                .addContainerGap())
            .addGroup(BookingMenuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookingsLabel)
                    .addGroup(BookingMenuPanelLayout.createSequentialGroup()
                        .addComponent(BookingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveBookingButton)
                            .addComponent(AddBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        BookingMenuPanelLayout.setVerticalGroup(
            BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingMenuLabel)
                    .addComponent(MainMenuButtonB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BookingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingMenuPanelLayout.createSequentialGroup()
                        .addComponent(AddBookingButton)
                        .addGap(5, 5, 5)
                        .addComponent(RemoveBookingButton))
                    .addComponent(BookingScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GuestMenuPanel.setMinimumSize(new java.awt.Dimension(330, 173));

        GuestMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GuestMenuLabel.setText("Guest Menu");

        MainMenuButtonG.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MainMenuButtonG.setText("Main Menu");

        GuestTextArea.setEditable(false);
        GuestTextArea.setColumns(30);
        GuestTextArea.setRows(5);
        GuestScrollPane.setViewportView(GuestTextArea);

        GuestsLabel.setText("Guests:");

        AddGuestButton.setText("Add");
        AddGuestButton.setActionCommand("AddG");

        RemoveGuestButton.setText("Remove");
        RemoveGuestButton.setActionCommand("RemoveG");

        javax.swing.GroupLayout GuestMenuPanelLayout = new javax.swing.GroupLayout(GuestMenuPanel);
        GuestMenuPanel.setLayout(GuestMenuPanelLayout);
        GuestMenuPanelLayout.setHorizontalGroup(
            GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GuestMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainMenuButtonG)
                .addContainerGap())
            .addGroup(GuestMenuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuestsLabel)
                    .addGroup(GuestMenuPanelLayout.createSequentialGroup()
                        .addComponent(GuestScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveGuestButton)
                            .addComponent(AddGuestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        GuestMenuPanelLayout.setVerticalGroup(
            GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuestMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuestMenuLabel)
                    .addComponent(MainMenuButtonG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuestsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GuestMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GuestMenuPanelLayout.createSequentialGroup()
                        .addComponent(AddGuestButton)
                        .addGap(5, 5, 5)
                        .addComponent(RemoveGuestButton))
                    .addComponent(GuestScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BookingMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GuestMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(RoomMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BookingMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GuestMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(RoomMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addActionListener(ActionListener listener) {
        this.AddBookingButton.addActionListener(listener);
        this.AddGuestButton.addActionListener(listener);
        this.AddRoomButton.addActionListener(listener);
        this.BookingMenuButton.addActionListener(listener);
        this.GuestMenuButton.addActionListener(listener);
        this.MainMenuButtonB.addActionListener(listener);
        this.MainMenuButtonG.addActionListener(listener);
        this.MainMenuButtonR.addActionListener(listener);
        this.RemoveBookingButton.addActionListener(listener);
        this.RemoveGuestButton.addActionListener(listener);
        this.RemoveRoomButton.addActionListener(listener);
        this.RoomMenuButton.addActionListener(listener);
        this.QuitButton.addActionListener(listener);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddBookingButton;
    public javax.swing.JButton AddGuestButton;
    public javax.swing.JButton AddRoomButton;
    public javax.swing.JButton BookingMenuButton;
    public javax.swing.JLabel BookingMenuLabel;
    public javax.swing.JPanel BookingMenuPanel;
    public javax.swing.JScrollPane BookingScrollPane;
    public javax.swing.JTextArea BookingTextArea;
    public javax.swing.JLabel BookingsLabel;
    public javax.swing.JButton GuestMenuButton;
    public javax.swing.JLabel GuestMenuLabel;
    public javax.swing.JPanel GuestMenuPanel;
    public javax.swing.JScrollPane GuestScrollPane;
    public javax.swing.JTextArea GuestTextArea;
    public javax.swing.JLabel GuestsLabel;
    public javax.swing.JLabel HotelBookingSystemLabel;
    public javax.swing.JButton MainMenuButtonB;
    public javax.swing.JButton MainMenuButtonG;
    public javax.swing.JButton MainMenuButtonR;
    public javax.swing.JPanel MainMenuPanel;
    public javax.swing.JButton QuitButton;
    public javax.swing.JButton RemoveBookingButton;
    public javax.swing.JButton RemoveGuestButton;
    public javax.swing.JButton RemoveRoomButton;
    public javax.swing.JButton RoomMenuButton;
    public javax.swing.JLabel RoomMenuLabel;
    public javax.swing.JPanel RoomMenuPanel;
    public javax.swing.JScrollPane RoomScrollPane;
    public javax.swing.JTextArea RoomTextArea;
    public javax.swing.JLabel RoomsLabel;
    public javax.swing.JLabel SelectMenuLabel;
    // End of variables declaration//GEN-END:variables

    public void showMainMenu() {
        RoomMenuPanel.setVisible(false);
        GuestMenuPanel.setVisible(false);
        BookingMenuPanel.setVisible(false);
        MainMenuPanel.setVisible(true);
    }

    public void closeWindow() {
        setVisible(false);
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    public void showGuestMenu() {
        MainMenuPanel.setVisible(false);
        GuestMenuPanel.setVisible(true);
    }

    public void showRoomMenu() {
        MainMenuPanel.setVisible(false);
        RoomMenuPanel.setVisible(true);
    }

    public void showBookingMenu() {
        MainMenuPanel.setVisible(false);
        BookingMenuPanel.setVisible(true);
    }

    // Creates Pop-Up windows asking user to input a String:
    public String getUserInputString(String question, String defInput) {
        String result;
        try {
            result = JOptionPane.showInputDialog(null, question, defInput).trim();
        } catch (NullPointerException ex) {
            return null; // Return null if 'cancel' is clicked.
        }
        return result;
    }

    // Creates a Pop-Up window asking user to input an Integer (and validates input):
    public Integer getUserInputInt(String question, String defInput) {
        String strInput;
        Integer result;
        strInput = JOptionPane.showInputDialog(null, question, defInput);
        if (strInput == null) {
            return null; // Return null if 'cancel' is clicked.
        }
        try {
            result = Integer.valueOf(strInput);
        } catch (NumberFormatException ex) {
            showMessagePopUp("Invalid Input: Must be an Integer. Try again");
            result = getUserInputInt(question, defInput); // prompt user again.
            return result;
        }
        return result;
    }

    // Creates Pop-Up windows asking user to select an object from a list and returns to caller:
    public Object getUserSelection(String prompt, String title, Object[] options, String defInput) {
        Object result;
        result = JOptionPane.showInputDialog(null, prompt, title, JOptionPane.QUESTION_MESSAGE, null, options, defInput);
        return result;
    }

    // Creates a Pop-Up window displaying a message to user:
    public void showMessagePopUp(String message) {
        JOptionPane.showMessageDialog(null, message);
    }

    @Override
    public void update(Observable obs, Object obj) {
        if (obj.getClass() == Guests.class) { //if obj is a Guests class, update textArea that displays the list of guests.
            Guests guests = (Guests) obj;
            this.GuestTextArea.setText(guests.toString());
        } else if (obj.getClass() == Rooms.class) {//if obj is a Rooms class, update textArea that displays the list of rooms.
            Rooms rooms = (Rooms) obj;
            this.RoomTextArea.setText(rooms.toString());
        } else if (obj.getClass() == Bookings.class) {//if obj is a Bookings class, update textArea that displays the list of bookings.
            Bookings bookings = (Bookings) obj;
            this.BookingTextArea.setText(bookings.toString());
        }
    }
}
